### ISSUE TITLE
Add base url to configuration

### ISSUE THREAD

**Issue by nickarsar** [tumainimosha/laravel-notifications-infobip#3]
[This page](https://dev.infobip.com/getting-started/base-url) shows how to add a personal domain.

This feature is not available in the current [configuration](https://github.com/tumainimosha/laravel-notifications-infobip/blob/master/src/Infobip.php#L15).

But [in the main library](https://github.com/infobip/infobip-api-php-client/blob/master/infobip/api/configuration/BasicAuthConfiguration.php#L12) there is such an opportunity.
# #

**Comment by tumainimosha** [comment]
pull request on this issue has been merged
